version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    volumes:
      - ./www:/var/www/html  # Mount your project directory
    ports:
      - "8080:80"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DB: mydatabase
    networks:
      - app-network

  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    networks:
      - app-network
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - db
networks:
  app-network:
    driver: bridge

volumes:
  db_data:
